### ISSUE TITLE
script.sh install should install prerequisite packages but does not; instead it errors with: config/variables.cfg: line 31: jq: command not found

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go-scripts-mainnet#10]
When script.sh is called with the install parameter, line #32 of script.sh invokes a function named prerequisites found in config/functions.cfg.

Line #13 in config/functions.cfg is within functions prepequisites.

At that line, the code is supposed to install the following packages using apt-get:
git rsync curl zip unzip jq gcc wget

If jq is not present on a system and script.sh was run with the install parameter, then jq should be installed. 

On line #13, apt-get is invoked twice.  The second invocation of apt-get is preceeded by &&.  && is a conditional operator that invokes the following command if the previous one was successful.  Therefore since jq was not installed, it follows that the exit code from the first invocation of apt-get was not zero.  

If success of the first invocation of apt-get is crucial to the success of the installation, then the exit code of the apt-get command should be captured and interpreted so that an appropriate error message can be displayed.  This would allow the operator a chance to correct the issue and retry the install.

**Comment by valentin-lup** [comment]
Sorry for the late answer. This issue has been fixed.
