### ISSUE TITLE
'github_pull' fails when no identity file exists

### ISSUE THREAD

**Issue by flyingbasalt** [ElrondNetwork/elrond-go-scripts-mainnet#4]
`github_pull` fails when it tries to backup `~/elrond-go-scripts-mainnet/config/identity` which I don't have because I don't use the remote install functionality.

**Comment by valentin-lup** [comment]
Good catch ! Will fix ASAP ! Thanks

**Comment by valentin-lup** [comment]
fixed by "fix-github-pull" PR
