### ISSUE TITLE
script.sh get_logs creates files named: elrond-node-0-null.log

### ISSUE THREAD

**Issue by frankf1957** [ElrondNetwork/elrond-go-scripts-mainnet#9]
script.sh get_logs creates files named: elrond-node-0-null.log, but the string "null" should be the node BLS key obtained from the node -rest-api-interface

please update line #306 in script.sh
from:
LOGSPUBLIC=$(curl -s http://127.0.0.1:$LOGSAPIPORT/node/status | jq -r .details.erd_public_key_block_sign | head -c 12)
to:
LOGSPUBLIC=$(curl -s http://127.0.0.1:$LOGSAPIPORT/node/status | jq -r .data.metrics.erd_public_key_block_sign | head -c 12)

**Comment by valentin-lup** [comment]
Great catch ! Thank you ! Will fix asap !

**Comment by valentin-lup** [comment]
Fixed with latest pull request.
